version: '3.8'
services:
  mysql:
    container_name: alphadb_mysql
    image: mysql:8
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    networks:
      - db_server
  

  phpmyadmin:
    container_name: alphadb_phpmyadmin
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: test 
    networks:
      - db_server

networks:
  db_server:
volumes:
  mysql_data:
