version: "3.8"
services:
  mysql:
    container_name: alphadb_mysql
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./scripts/init-dev-db.sql:/docker-entrypoint-initdb.d/init.sql
      - alphadb_mysql:/var/lib/mysql
    ports:
      - "333:3306"
    networks:
      - alphadb_network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 10

  postgres:
    container_name: alphadb_postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: test
    volumes:
      - ./scripts/init-dev-db-postgres.sql:/docker-entrypoint-initdb.d/init.sql
      - alphadb_postgres:/var/lib/postgresql
    ports:
      - "544:5432"
    networks:
      - alphadb_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s

networks:
  alphadb_network:
volumes:
  alphadb_mysql:
  alphadb_postgres:
