version: '3.7'
services:
  mysql:
    image: mysql:8
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    networks:
      - db_server
    
  phpmyadmin:
    depends_on:
      - mysql
    image: arm64v8/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: test 
    networks:
      - db_server
networks:
  db_server:
volumes:
  db_data:
