version: "3.8"
services:
  mysql:
    container_name: alphadb_mysql
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./scripts/init-dev-db.sql:/docker-entrypoint-initdb.d/init.sql
      - alphadb_mysql:/var/lib/mysql
    ports:
      - "333:3306"
    networks:
      - alphadb_network

  phpmyadmin:
    container_name: alphadb_phpmyadmin
    depends_on:
      - mysql
    image: phpmyadmin
    restart: always
    ports:
      - "888:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: test
    networks:
      - alphadb_network

networks:
  alphadb_network:
volumes:
  alphadb_mysql:
