[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "mysql-connector-python==8.1.0"
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
pythonpath = "."

[tool.black]
line-length = 220
