[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
alphadb = { path = "../alphadb" }
inquire = "0.7.5"
colored = "2.1.0"
toml = "0.8.19"
serde = "1.0.210"
serde_derive = "1.0.210"
home = "0.5.9"
rand = "0.8.5"
