name: Build Node binaries

on:
  workflow_call:

jobs:
  build:
    name: Build Node binaries
    if: startsWith(github.ref, 'refs/tags/')
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        # os: [macos-latest, windows-latest, ubuntu-latest]
        
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org

      - name: Install Deps
        # run: cargo install cross
        run: |
          npm install --global typescript
          npm install --global yarn

      - name: Build node package
        run: |
          python scripts/build-scripts/node.py ${{ github.ref_name }}

      - name: Store Node binary
        uses: actions/upload-artifact@v4
        with:
          name: node-bin-${{ matrix.os }}
          path: ./src/node/node-bin/
