name: Development release

on:
  push:
    tags:
      - "v1.0.0-dev.*"

jobs:
  build-py:
    uses: ./.github/workflows/build-py.yml

  publish-py:
    name: Publish to Test PyPI
    strategy:
      matrix:
        # os: [macos-latest, windows-latest, ubuntu-22.04]
        # python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
        os: [ubuntu-22.04]
        python-version: ["3.12"]

    needs:
      - build-py
    runs-on: ubuntu-latest
    environment:
      name: test
      url: https://test.pypi.org/project/alphadb/
    permissions:
      id-token: write
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-api-${{ matrix.os }}-${{ matrix.python-version }}
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository_url: https://test.pypi.org/legacy/
