name: Build Python package

on:
  workflow_call:

jobs:
  release:
    name: Sign with Sigstore and upload them to GitHub Release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Download Linux Node binaries
        uses: actions/download-artifact@v4
        with:
          name: node-bin-ubuntu-latest
          path: node-bin/

      - name: Download MacOS Node binaries
        uses: actions/download-artifact@v4
        with:
          name: node-bin-macos-latest
          path: node-bin/

      - name: Download Windows Node binaries
        uses: actions/download-artifact@v4
        with:
          name: node-bin-windows-latest
          path: node-bin/

      - name: Download Linux CLI binaries
        uses: actions/download-artifact@v4
        with:
          name: cli-bin-ubuntu-20.04
          # name: cli-bin-ubuntu-latest
          path: cli-bin/

      - name: Download MacOS CLI binaries
        uses: actions/download-artifact@v4
        with:
          name: cli-bin-macos-latest
          path: cli-bin/

      - name: Download Windows CLI binaries
        uses: actions/download-artifact@v4
        with:
          name: cli-bin-windows-latest
          path: cli-bin/

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          if ! gh release view "${{ github.ref_name }}" --repo "${{ github.repository}}" >/dev/null 2>&1; then
            gh release create -p "${{ github.ref_name }}" --repo "${{ github.repository }}" --generate-notes
          else
            echo "Release '${{ github.ref_name }}' already exists."
          fi

      - name: Upload CLI binaries
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh release upload '${{ github.ref_name }}' cli-bin/** --repo '${{ github.repository }}'

      - name: Upload Node binaries
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh release upload '${{ github.ref_name }}' node-bin/** --repo '${{ github.repository }}'
