name: Release for production

on:
  push:
    tags:
      v1.0.0-dev.*

jobs:
  # publish-py:
    # uses: ./.github/workflows/publish-py.yml
    
  # publish-cargo:
    # uses: ./.github/workflows/publish-cargo.yml

  publish-node:
    uses: ./.github/workflows/publish-node.yml
  
  publish-github-release:
    needs: publish-node
    uses: ./.github/workflows/publish-github-release.yml

