name: Release for production

on: push

jobs:
  build-py:
    name: Build Python API
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install pypa/build
        run: python3 -m  pip install build --user
      - name: Build binary wheel and source tarball
        run: python3 scripts/build-scripts/pypi.py &{{ github.ref_name }}
      - name: Store the distribution packages
        uses: actions/upload-artifact@v3
        with:
          name: python-package-distributions
          path: dist/

  build-cli:
    name: Build distribution
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      
      - name: Install pyinstaller
        run: python3 -m pip install pyinstaller
      - name: Build executable
        run: python3 scripts/build-scripts/linux-amd64.py &{{ github.ref_name }}           
      - name: Store the executable
        uses: actions/upload-artifact@v3
        with:
          name: cli-executable-linux
          path: dist/
      
  publish-to-pypi:
    name: Publish to PyPI
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - build-py
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/alphadb
    permissions:
      id-token: write
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v3
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  github-release:
    name: Sign with Sigstore and upload them to GitHub Release
    needs:
      - publish-to-pypi
      - build-cli
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v3
        with:
          name: python-package-distributions
          path: dist/
      - name: Sign the dists with Sigstore
        uses: sigstore/gh-action-sigstore-python@v1.2.3
        with:
          inputs: >-
            ./dist/*.tar.gz
            ./dist/*.whl
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh release create -p '${{ github.ref_name }}' --repo '${{ github.repository }}' --generate-notes;

      - name: Upload artifact signatures to GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: gh release upload '${{ github.ref_name }}' dist/** --repo '${{ github.repository }}'
