name: Tests

on:
  push:
    branches: "main"

jobs:
  rust-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Start Docker Compose services
        run: docker compose up -d

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Test with Cargo
        run: |
          cd src/alphadb
          cargo test --features mysql,postgres

      - name: Stop Docker Compose services
        if: always()
        run: docker compose down

  python-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Start Docker Compose services
        run: docker compose up -d

      - name: Set up Python
        uses: actions/setup-python@v6

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Test with Pytest
        run: |
          cd src/py
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          maturin develop 
          pytest

      - name: Stop Docker Compose services
        if: always()
        run: docker compose down

  node-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Start Docker Compose services
        run: docker compose up -d

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Test with Vitest
        run: |
          cd src/node
          yarn
          yarn build
          yarn test

      - name: Stop Docker Compose services
        if: always()
        run: docker compose down
