name: Tests

on:
  push:
    branches: "main"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  rust-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Start Docker Compose services
        run: docker compose up -d --wait

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Test with Cargo
        run: |
          cd src/alphadb
          cargo test --features mysql,postgres

      - name: Stop Docker Compose services
        if: always()
        run: docker compose down -v

  python-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        engine: [mysql, postgres]

    steps:
      - uses: actions/checkout@v6
      - name: Start Docker Compose services
        run: docker compose up -d --wait

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Test with Pytest
        run: |
          cd src/py
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          maturin develop --features ${{ matrix.engine }}
          ALPHADB_ENGINE=${{ matrix.engine }} pytest

      - name: Stop Docker Compose services
        if: always()
        run: docker compose down -v

  node-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        engine: [mysql, postgres]

    steps:
      - uses: actions/checkout@v6
      - name: Start Docker Compose services
        run: docker compose up -d --wait

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Test with Vitest
        run: |
          cd src/node
          yarn --ignore-scripts
          yarn test:${{ matrix.engine }}

      - name: Stop Docker Compose services
        if: always()
        run: docker compose down -v
