name: Tests

on:
  push:
    branches: "main"

jobs:
  rust-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: adambirds/docker-compose-action@v1.5.0

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Test with Cargo
        run: |
          cd src/alphadb
          cargo test

  python-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: adambirds/docker-compose-action@v1.5.0

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Test with Pytest
        run: |
          cd src/py
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          maturin develop 
          pytest

  node-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: adambirds/docker-compose-action@v1.5.0

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Test with Vitest
        run: |
          cd src/node
          yarn
          yarn build
          yarn test
