name: Publish AlphaDB to TestPyPI

on:
  push:
    branches: "latest"

jobs:
  build:
    name: Build distribution
    runs-on: unbuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install pypa/build
        run: >-
          python3 -m  
          pip install
          build
          --user
      - name: Build binary wheel and source tarball
        run: python3 -m build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v3
        with:
          name: python-package-distributions
          path: dist/

  publish-testpypi:
    name: Publish to TestPyPI
    needs:
      - build
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/alphadb

    permissions:
      id-token: write

    steop:
      - name: Download all dists
        uses: actions/download-artifact@v3
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy
